### ISSUE TITLE
TypeError: Cannot read property 'transcript' of null

### ISSUE THREAD

**Issue by lukedhlee** [Henguin1001/Subtitle-Scraper#1]
When I use 'subtitle_scraper' just as it is provided at _README.md_, 
```
var express = require('express');
var router = express.Router();
var subtitle_scraper = require('subtitle_scraper');

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

router.get('/download', function(req, res) {
  // Will be called when the download starts.
  // downloadSubtitles();
  subtitle_scraper("9XQfYKYO380", function(err, arr, raw, url){
    // err contains any errors straight from the "Request" module
    // arr contains the json equivalent of the xml response of the subtitles
    // url is the url queryed to get the subtitles
    console.log(arr.transcript.text);
    // arr.transcript.text will probably be the only useful part of "arr"
  });
  res.render('index', { title: 'Please wait' });
})

module.exports = router;
```

I get following errors: 
```
2019-02-04T15:47:46.296773+00:00 app[web.1]: /app/routes/index.js:35
2019-02-04T15:47:46.296776+00:00 app[web.1]: console.log(arr.transcript.text);
2019-02-04T15:47:46.296778+00:00 app[web.1]: ^
2019-02-04T15:47:46.296779+00:00 app[web.1]:
2019-02-04T15:47:46.296781+00:00 app[web.1]: TypeError: Cannot read property 'transcript' of null
2019-02-04T15:47:46.296783+00:00 app[web.1]: at /app/routes/index.js:35:21
2019-02-04T15:47:46.296789+00:00 app[web.1]: at Request._callback (/app/node_modules/subtitle_scraper/index.js:36:14)
2019-02-04T15:47:46.296790+00:00 app[web.1]: at Request.self.callback (/app/node_modules/request/request.js:185:22)
2019-02-04T15:47:46.296792+00:00 app[web.1]: at Request.emit (events.js:189:13)
2019-02-04T15:47:46.296793+00:00 app[web.1]: at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
2019-02-04T15:47:46.296795+00:00 app[web.1]: at Request.emit (events.js:189:13)
2019-02-04T15:47:46.296796+00:00 app[web.1]: at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
2019-02-04T15:47:46.296798+00:00 app[web.1]: at Object.onceWrapper (events.js:277:13)
2019-02-04T15:47:46.296799+00:00 app[web.1]: at IncomingMessage.emit (events.js:194:15)
2019-02-04T15:47:46.296801+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1103:12)
2019-02-04T15:47:46.306821+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-02-04T15:47:46.307401+00:00 app[web.1]: npm ERR! errno 1
2019-02-04T15:47:46.309176+00:00 app[web.1]: npm ERR! wassub-clip@0.0.0 start: `node ./bin/www`
2019-02-04T15:47:46.309390+00:00 app[web.1]: npm ERR! Exit status 1
2019-02-04T15:47:46.309733+00:00 app[web.1]: npm ERR!
2019-02-04T15:47:46.309947+00:00 app[web.1]: npm ERR! Failed at the wassub-clip@0.0.0 start script.
2019-02-04T15:47:46.310140+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Does anyone know how to address this issue? Thanks!

**Comment by lukedhlee** [comment]
Plus, just found that: 

```
2019-02-04T15:58:12.943795+00:00 app[web.1]: err:  null
2019-02-04T15:58:12.943866+00:00 app[web.1]: arr:  null
2019-02-04T15:58:12.943959+00:00 app[web.1]: raw:  undefined
2019-02-04T15:58:12.944010+00:00 app[web.1]: url:  undefined
```
Am I missing something? Am using the example @Henguin1001 used: https://www.youtube.com/watch?v=9XQfYKYO380

**Comment by Henguin1001** [comment]
The function is outputting an empty array. This is probably because the method the scraper originally used no longer works after youtube has been updated over the past 3 years. You are welcome to try to fix it. 
The way I originally did it was to watch the networks tab in chrome and see what happens when you press the cc button. It should show a request to an endpoint that looks like this: https://www.youtube.com/api/timedtext?sparams=asr_langs%2Ccaps%2Cv%2Cxoaf%2Cxorp%2Cexpire&xorp=True&caps=asr&v=9XQfYKYO380&hl=en&xoaf=1&expire=1549356675&key=yttt1&signature=983C8FCE16822ABAB36803FA35AFBC81E2BC8120.4B48C94AB52328EECF9395C51B11466A2B2ECC8F&asr_langs=pt%2Cen%2Cko%2Cru%2Cit%2Cde%2Cfr%2Cnl%2Cja%2Ces&kind=asr&lang=en&fmt=srv3 
which returns the desired xml data. The api will need to make a request to the page to find this link then follow it.

**Comment by lukedhlee** [comment]
It works! Thanks for your help!
